# Generated by Django 5.0.4 on 2024-04-04 15:15

import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f4e625d2-192a-422a-9f85-34cca71cf305'), primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('carbs', models.FloatField(db_column='carbs')),
                ('protein', models.FloatField(db_column='protein')),
                ('fats', models.FloatField(db_column='fats')),
                ('calories', models.IntegerField(db_column='calories')),
            ],
            options={
                'db_table': 'MAE_FOOD',
            },
        ),
    ]
